org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.64
neo_version_range=[21.1.0,)
loader_version_range=[1,)

mod_id=fluxnetworks
mod_version=8.1.0-SNAPSHOT

mekanism_version=1.21.1-10.7.7.64
top_version=1.21_neo-12.0.4-6
jei_version=19.21.0.247
gregtech_ceu_version=1.4.6
curios_version=9.5.0+1.21.1
modernui_version=1.21.1-3.13.0.+
modernui_core_version=3.13.0
